apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-sdk-config
  namespace: default
data:
  OTEL_SERVICE_NAME: luckystreak
  OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
  OTEL_EXPORTER_OTLP_ENDPOINT: agent-grafana-agent
  OTEL_TRACES_EXPORTER: otlp
  OTEL_METRICS_EXPORTER: otlp
  OTEL_LOGS_EXPORTER: otlp
  OTEL_NODE_RESOURCE_DETECTORS: all
  OTEL_LOG_LEVEL: verbose
  
