apiVersion: v1
kind: Pod
metadata:
  name: sample-svc-instrumented
  labels:
    app.kubernetes.io/name: sample-svc-instrumented
spec:
  containers:
  - name: sample-svc-instrumented
    image: moxious/sample-svc-instrumented
    imagePullPolicy: Always
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
    ports:
    - containerPort: 8080
    envFrom:
    - configMapRef:
        name: otel-sdk-config
---
apiVersion: v1
kind: Service
metadata:
  name: sample-svc
spec:
  selector:
    app.kubernetes.io/name: sample-svc-instrumented
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
